AWSTemplateFormatVersion: "2010-09-09"
Description: Template for Photo Album
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties: 
      AccessControl: PublicRead
      BucketName: front-end-bucket-6
      WebsiteConfiguration:
        IndexDocument: index.html
      # LoggingConfiguration: 
      #   DestinationBucketName: codepipeline-cloudtrail-placeholder-bucket-us-east-1
      VersioningConfiguration: 
        Status: Enabled
    
  S3Bucketphotos:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties: 
      AccessControl: PublicRead
      BucketName: s3-bucket-6

  PhotobucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: s3-bucket-6
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
            # {
            #     "Sid": "AddPerm",
            #     "Effect": "Allow",
            #     "Principal": "*",
            #     "Action": "s3:PutObject",
            #     "Resource": "arn:aws:s3:::photo-storage-bucket/*"
            # },
            {
                "Sid": "AddPerm",
                "Effect": "Allow",
                "Principal": {
                    "AWS": "*"
                },
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::s3-bucket-6/*"
            }
        ]
      }

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Body: 
        swagger: "2.0"
        info:
          description: "AI Photo Search application, built during the Cloud and Big Data course\
            \ at Columbia University."
          version: "1.0.0"
          title: "AI Photo Search"
        host: "432b4buetg.execute-api.us-east-1.amazonaws.com"
        basePath: "/stage1"
        schemes:
        - "https"
        paths:
          /search:
            get:
              operationId: "searchPhotos"
              produces:
              - "application/json"
              parameters:
              - name: "q"
                in: "query"
                required: false
                type: "string"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/SearchResponse"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                "500":
                  description: "500 response"
                  schema:
                    $ref: "#/definitions/Error"
                "403":
                  description: "403 response"
                  schema:
                    $ref: "#/definitions/Error"
            options:
              consumes:
              - "application/json"
              produces:
              - "application/json"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/SearchResponse"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
          /upload/{folder}/{item}:
            put:
              parameters:
              - name: "item"
                in: "path"
                required: true
                type: "string"
              - name: "folder"
                in: "path"
                required: true
                type: "string"
              - name: "x-amz-meta-customLabels"
                in: "header"
                required: false
                type: "string"
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
            options:
              produces:
              - "application/json"
              parameters:
              - name: "Access-Control-Allow-Origin"
                in: "header"
                required: false
                type: "string"
              - name: "folder"
                in: "path"
                required: true
                type: "string"
              - name: "item"
                in: "path"
                required: true
                type: "string"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Photo"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
        definitions:
          Error:
            type: "object"
            properties:
              code:
                type: "integer"
                format: "int32"
              message:
                type: "string"
          Photo:
            type: "object"
            properties:
              url:
                type: "string"
              labels:
                type: "array"
                items:
                  type: "string"
          SearchResponse:
            type: "object"
            properties:
              results:
                type: "array"
                items:
                  $ref: "#/definitions/Photo"

  ElasticSearch:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
        DomainName: photo-domain-2
        EBSOptions:
            EBSEnabled: true
            VolumeSize: 10
        ElasticsearchClusterConfig:
            InstanceType: t2.small.elasticsearch
        ElasticsearchVersion: '7.1'

 
 

  
 


 